# Generated by Django 3.1.3 on 2020-11-10 21:50

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('header', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to=games.models.image_upload)),
                ('content', models.TextField()),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
            ],
        ),
    ]
