# Generated by Django 3.1.3 on 2020-11-11 00:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
