# Generated by Django 3.1.3 on 2020-11-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20201111_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='content',
            field=models.TextField(),
        ),
    ]
